# Generated by Django 6.0.4 on 2026-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('entity_type', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand'), ('campaign', 'Campaign')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
            ],
            options={
                'db_table': 'tag',
                'unique_together': {('client', 'name', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='TagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand'), ('campaign', 'Campaign')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='configurations.tag')),
            ],
            options={
                'db_table': 'tag_mapping',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='tag_mapping_entity__3fd7f0_idx')],
                'unique_together': {('tag', 'entity_type', 'entity_id')},
            },
        ),
    ]
