# Generated by Django 6.0.4 on 2026-04-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0002_tag_tagmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='adformat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_ad_formats', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='platform',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_platforms', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='adformat',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('name', 'platform'), name='unique_global_ad_format'),
        ),
        migrations.AddConstraint(
            model_name='adformat',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'name', 'platform'), name='unique_client_ad_format'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('name',), name='unique_global_platform'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'name'), name='unique_client_platform'),
        ),
    ]
