# Generated by Django 6.0.4 on 2026-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('campaign', 'Campaign'), ('creator', 'Creator'), ('brand', 'Brand'), ('payout', 'Payout')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='employees.employee')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='notes.comment')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='comment_entity__b5998d_idx')],
            },
        ),
    ]
