# Generated by Django 6.0.4 on 2026-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='context',
            field=models.CharField(choices=[('note', 'Note'), ('brand_said', 'Brand Said'), ('creator_said', 'Creator Said'), ('agency_pitch', 'Agency Pitch')], default='note', max_length=20),
        ),
    ]
