# Generated by Django 6.0.4 on 2026-04-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('configurations', '0001_initial'),
        ('creators', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='creators.creator'),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='campaign_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='campaigns.campaigncreator'),
        ),
        migrations.AddField(
            model_name='campaignmetric',
            name='campaign_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaigncontent'),
        ),
        migrations.AddField(
            model_name='campaignrequirement',
            name='ad_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_requirements', to='configurations.adformat'),
        ),
        migrations.AddField(
            model_name='campaignrequirement',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignrequirement',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_requirements', to='configurations.platform'),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='campaigns.campaignrequirement'),
        ),
        migrations.AddField(
            model_name='campaignstatuslog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncreator',
            unique_together={('campaign', 'creator')},
        ),
    ]
