# Generated by Django 6.0.4 on 2026-04-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to='employees.employee')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payouts', to='employees.employee')),
            ],
            options={
                'db_table': 'payout',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payouts.payout')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='PayoutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_configs', to='campaigns.campaigncreator')),
            ],
            options={
                'db_table': 'payout_config',
            },
        ),
        migrations.AddField(
            model_name='payout',
            name='payout_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payouts.payoutconfig'),
        ),
        migrations.CreateModel(
            name='PayoutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('trigger_condition', models.TextField(blank=True, help_text='Condition to achieve this milestone')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('achieved', 'Achieved'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='payouts.payoutconfig')),
            ],
            options={
                'db_table': 'payout_milestone',
            },
        ),
        migrations.AddField(
            model_name='payout',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='payouts.payoutmilestone'),
        ),
        migrations.CreateModel(
            name='PayoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type_code', models.CharField(choices=[('advance', 'Advance'), ('goal_based', 'Goal-Based'), ('one_time', 'One-Time'), ('completion', 'Completion Only'), ('hybrid', 'Hybrid')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
            ],
            options={
                'db_table': 'payout_type',
                'unique_together': {('client', 'type_code')},
            },
        ),
        migrations.AddField(
            model_name='payoutconfig',
            name='payout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_configs', to='payouts.payouttype'),
        ),
    ]
