# Generated by Django 6.0.4 on 2026-04-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstin',
            field=models.CharField(blank=True, help_text='GSTIN of the creator', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_certificate_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tds_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='gst_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payout',
            name='net_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('neft', 'NEFT'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payout',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payout',
            name='tds_section',
            field=models.CharField(blank=True, help_text='TDS section e.g. 194R, 194J, 194C', max_length=10),
        ),
        migrations.AddField(
            model_name='payout',
            name='utr_number',
            field=models.CharField(blank=True, help_text='Bank transaction reference', max_length=50),
        ),
    ]
