# Generated by Django 6.0.4 on 2026-04-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'Super Admin'), ('employee', 'Employee')], max_length=10)),
                ('actor_id', models.BigIntegerField()),
                ('actor_name', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('void', 'Void'), ('restore', 'Restore'), ('login', 'Login'), ('export', 'Export'), ('approve', 'Approve')], max_length=10)),
                ('entity_type', models.CharField(help_text='e.g., Brand, Campaign, Employee', max_length=100)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Diff of changed fields')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context (IP, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.client')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', 'entity_type', 'entity_id'], name='audit_log_client__7a05cc_idx'), models.Index(fields=['actor_type', 'actor_id'], name='audit_log_actor_t_16ca8a_idx')],
            },
        ),
    ]
