# Generated by Django 6.0.4 on 2026-04-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('campaign', 'Campaign Report'), ('creator', 'Creator Report'), ('brand', 'Brand Report'), ('financial', 'Financial Report'), ('dashboard', 'Dashboard Snapshot')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter parameters used')),
                ('export_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], max_length=10)),
                ('file_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='employees.employee')),
            ],
            options={
                'db_table': 'saved_report',
                'ordering': ['-generated_at'],
            },
        ),
    ]
