# Generated by Django 6.0.4 on 2026-04-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employees/profiles/')),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to='employees.employee')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='roles.role')),
            ],
            options={
                'db_table': 'employee',
                'unique_together': {('client', 'email'), ('client', 'username')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
            ],
            options={
                'db_table': 'employee_tag',
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('grant', 'Grant'), ('deny', 'Deny')], max_length=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='employees.employee')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overrides', to='roles.permission')),
            ],
            options={
                'db_table': 'employee_permission_override',
                'unique_together': {('employee', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_mappings', to='employees.employee')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='employees.employeetag')),
            ],
            options={
                'db_table': 'employee_tag_mapping',
                'unique_together': {('employee', 'tag')},
            },
        ),
    ]
