# Generated by Django 6.0.4 on 2026-04-18 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other')], max_length=20)),
                ('language', models.JSONField(blank=True, default=list, help_text='List of languages')),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='creators/profiles/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_creators', to='employees.employee')),
            ],
            options={
                'db_table': 'creator',
                'unique_together': {('client', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CreatorFollowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_history', to='creators.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_histories', to='configurations.platform')),
            ],
            options={
                'db_table': 'creator_follower_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('ad_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_charges', to='configurations.adformat')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='creators.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_charges', to='configurations.platform')),
            ],
            options={
                'db_table': 'creator_charge',
                'unique_together': {('creator', 'platform', 'ad_format')},
            },
        ),
        migrations.CreateModel(
            name='CreatorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='creators.creator')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_domains', to='configurations.domain')),
            ],
            options={
                'db_table': 'creator_domain',
                'unique_together': {('creator', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='CreatorPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profile_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='creators.creator')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_platforms', to='configurations.platform')),
            ],
            options={
                'db_table': 'creator_platform',
                'unique_together': {('creator', 'platform')},
            },
        ),
    ]
