# Generated by Django 6.0.4 on 2026-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('creators', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='creator',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='creator',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creator',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='creator',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='creator',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='creator',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='creator',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creator',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CreatorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('aadhaar', 'Aadhaar'), ('gst_certificate', 'GST Certificate'), ('bank_proof', 'Bank Proof'), ('nda', 'NDA'), ('contract', 'Contract'), ('portfolio', 'Portfolio'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='creators/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='creators.creator')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.employee')),
            ],
            options={
                'db_table': 'creator_document',
            },
        ),
        migrations.CreateModel(
            name='MediaKitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('highlight_stats', models.JSONField(blank=True, default=dict, help_text='Key stats to highlight')),
                ('theme_color', models.CharField(default='#6366f1', max_length=7)),
                ('show_contact', models.BooleanField(default=False)),
                ('show_charges', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('custom_url_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_kit', to='creators.creator')),
            ],
            options={
                'db_table': 'media_kit_config',
            },
        ),
        migrations.CreateModel(
            name='MediaKitLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('portfolio', 'Portfolio'), ('case_study', 'Case Study'), ('press', 'Press'), ('other', 'Other')], default='other', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='creators.mediakitconfig')),
            ],
            options={
                'db_table': 'media_kit_link',
                'ordering': ['sort_order'],
            },
        ),
    ]
