# Generated by Django 6.0.4 on 2026-04-18 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_event', models.CharField(choices=[('campaign_created', 'Campaign Created'), ('campaign_stage_changed', 'Campaign Stage Changed'), ('content_submitted', 'Content Submitted'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('payout_requested', 'Payout Requested'), ('payout_approved', 'Payout Approved'), ('payout_paid', 'Payout Paid'), ('deadline_approaching', 'Deadline Approaching'), ('creator_assigned', 'Creator Assigned')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('title_template', models.CharField(help_text='Supports {campaign}, {creator}, etc.', max_length=255)),
                ('body_template', models.TextField(help_text='Supports {campaign}, {creator}, {brand}, etc.')),
                ('channels', models.JSONField(blank=True, default=list, help_text='e.g. ["in_app","email"]')),
                ('is_enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.client')),
            ],
            options={
                'db_table': 'notification_template',
                'unique_together': {('client', 'trigger_event')},
            },
        ),
    ]
